version: '3.9'
services:
  app:
    image: fajjarnr/bwf-micro-backend:service-course
    container_name: bwf-service-course
    environment:
      - APP_NAME=service_course
      - APP_KEY=base64:6zrLF/wEs3hO4AlX+BReJ803ec4zR//FWEOz6ZSgYuw=
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=bwf-micro.cyh0sfq8vv2a.ap-southeast-3.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=service_course
      - DB_USERNAME=admin
      - DB_PASSWORD=rahasia123
      - SERVICE_USER_URL=bwf-service-user
      - SERVICE_ORDER_PAYMENT_URL=bwf-service-payment
    restart: always
    tty: true
    ports:
      - 8080:8080
    networks:
      - service-course-network

networks:
  service-course-network:
