apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: bwf
data:
  APP_NAME: "service_course"
  APP_ENV: "local"
  APP_KEY: "base64:6zrLF/wEs3hO4AlX+BReJ803ec4zR//FWEOz6ZSgYuw="
  APP_DEBUG: "true"
  APP_URL: http://bwf-service-course

  LOG_CHANNEL: stack
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: bwf-micro.cyh0sfq8vv2a.ap-southeast-3.rds.amazonaws.com
  DB_PORT: "3306"
  DB_DATABASE: service_course
  DB_USERNAME: admin
  DB_PASSWORD: rahasia123

  SERVICE_USER_URL: http://bwf-service-user
  SERVICE_ORDER_PAYMENT_URL: http://bwf-service-payment
