apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: bwf
data:
  APP_NAME: "service_course"
  APP_KEY: "base64:6zrLF/wEs3hO4AlX+BReJ803ec4zR//FWEOz6ZSgYuw="
  APP_URL: http://bwf-service-course

  LOG_CHANNEL: stack
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: service_course
  DB_USERNAME: root
  DB_PASSWORD: rahasia

  SERVICE_USER_URL: http://bwf-service-user
  SERVICE_ORDER_PAYMENT_URL: http://bwf-service-payment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwf-service-course
  namespace: bwf
  labels:
    app: bwf-service-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwf-service-course
  template:
    metadata:
      labels:
        app: bwf-service-course
    spec:
      containers:
        - name: bwf-service-course
          image: "fajjarnr/bwf-service-course:latest"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config

---
apiVersion: v1
kind: Service
metadata:
  name: bwf-service-course
  namespace: bwf
spec:
  selector:
    app: bwf-service-course
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
