apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwf-service-course
  namespace: bwf
spec:
  selector:
    matchLabels:
      app: bwf-service-course
  replicas: 1
  template:
    metadata:
      labels:
        app: bwf-service-course
    spec:
      containers:
        - name: bwf-service-course
          image: fajjarnr/bwf-service-course
          enviroment:
            - DB_CONNECTION: mysql
            - DB_HOSTNAME: bwf-micro.cyh0sfq8vv2a.ap-southeast-3.rds.amazonaws.com
            - DB_PORT: 3306
            - DB_NAME: service_course
            - DB_USERNAME: admin
            - DB_PASSWORD: rahasia12
            - SERVICE_USER_URL: bwf-service-user
            - SERVICE_ORDER_PAYMENT_URL: bwf-service-payment
          ports:
            - containerPort: 9000
        - name: nginx
          image: fajjarnr/bwf-service-course
          ports:
            - containerPort: 80
