apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwf-service-course
  namespace: bwf
  labels:
    app: bwf-service-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwf-service-course
  template:
    metadata:
      labels:
        app: bwf-service-course
    spec:
      containers:
        - name: bwf-service-course
          image: "fajjarnr/bwf-service-course:latest"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
